FROM debian:trixie
RUN apt-get update && apt-get install -y python3 python3-pip
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# Définir le répertoire de travail
WORKDIR /app
# Copier les fichiers de l'application dans le conteneur
COPY app/ /app/
# Installer les dépendances de l'application    
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt
# Commande pour exécuter l'application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
